const TILES = [
  {
    id: 0,
    badge: "STATEMENT",
    tag: "PEBBLE WASH",
    title: "River Pebble Wash Panel",
    description:
      "Smooth river pebbles set in a natural cement wash panel. Creates organic, tactile wall surfaces perfect for garden water features and zen gardens.",
    image: "./images/outdoor/Riverpebble3.jpg",
    gallery: [
      "./images/outdoor/Riverpebble1.jpg",
      "./images/outdoor/Riverpebble2.jpg",
      "./images/outdoor/Riverpebble4.jpg",
      "./images/outdoor/Riverpebble3.jpg",
    ],
    texture: "Stone",
    colours: 3,
    finishes: 1,
    finish: ["Natural"],
    sizes: ["300×300", "300×600"],
    surface: ["Weather Resistant", "Anti-Algae", "Frost Resistant"],
    colors: ["Grey", "Beige", "Cream"],
    colorsHex: { Grey: "#9fa3aa", Beige: "#d8c9a3", Cream: "#f0ebe0" },
    colorImages: {
      Grey: "./images/outdoor/Riverpebble2.jpg",
      Beige: "./images/outdoor/Riverpebble1.jpg",
      Cream: "./images/outdoor/Riverpebble2.jpg",
    },
    finishImages: { Natural: "./images/outdoor/Riverpebble1.jpg" },
    sizeImages: {
      "300×300": "./images/outdoor/Riverpebble1.jpg",
      "300×600": "./images/outdoor/Riverpebble4.jpg",
    },
    features: [
      {
        icon: "fa-solid fa-water",
        title: "Water Feature Ready",
        desc: "Pebble surface is ideal for pool surrounds, water walls and zen garden features.",
      },
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "River pebble panels withstand direct rainfall and outdoor moisture exposure.",
      },
      {
        icon: "fa-solid fa-snowflake",
        title: "Frost Resistant",
        desc: "Dense natural pebble construction suitable for use in frost-prone regions.",
      },
      {
        icon: "fa-solid fa-leaf",
        title: "Anti-Algae",
        desc: "Surface treatment inhibits biological growth around water features and damp zones.",
      },
      {
        icon: "fa-solid fa-hand",
        title: "Tactile Surface",
        desc: "Rounded smooth pebbles create sensory, organic wall surfaces unlike any other tile.",
      },
      {
        icon: "fa-solid fa-spa",
        title: "Zen Aesthetic",
        desc: "Natural river pebble pattern complements Japanese, tropical and organic garden styles.",
      },
    ],
    tech: {
      Material: "River Pebble / Cement",
      "Water Absorption": "2–5%",
      "Frost Resistance": "Class F2",
      Finish: "Natural",
      "Breaking Strength": "> 700 N",
      Thickness: "15–25 mm",
      "Weight (per m²)": "30 kg",
      "Chemical Resistance": "Class B",
    },
  },
  {
    id: 1,
    badge: "POPULAR",
    tag: "WOOD EFFECT",
    title: "Driftwood Timber Plank",
    description:
      "Coastal driftwood aesthetic in weather-worn grey-brown tones. UV-stable porcelain delivers the warmth of wood without the maintenance.",
    image: "./images/outdoor/Driftwood.jpg",
    gallery: [
      "./images/outdoor/Driftwood1.jpg",
      "./images/outdoor/Driftwood2.png",
      "./images/outdoor/Driftwood3.jpg",
      "./images/outdoor/Driftwood4.jpg",
    ],
    texture: "Wood",
    colours: 3,
    finishes: 2,
    finish: ["Matt", "Natural"],
    sizes: ["150×600", "300×600", "600×1200"],
    surface: ["Weather Resistant", "UV Stable"],
    colors: ["Grey", "Beige", "Charcoal"],
    colorsHex: { Grey: "#9fa3aa", Beige: "#d8c9a3", Charcoal: "#2e2a26" },
    colorImages: {
      Grey: "./images/outdoor/Driftwood2.png",
      Beige: "./images/outdoor/Driftwood4.jpg",
      Charcoal: "./images/outdoor/Driftwood1.jpg",
    },
    finishImages: {
      Matt: "./images/outdoor/Driftwood1.jpg",
      Natural: "./images/outdoor/Driftwood3.jpg",
    },
    sizeImages: {
      "150×600": "./images/outdoor/Driftwood1.jpg",
      "300×600": "./images/outdoor/Driftwood2.png",
      "600×1200": "./images/outdoor/Driftwood4.jpg",
    },
    features: [
      {
        icon: "fa-solid fa-tree",
        title: "Wood Aesthetics",
        desc: "HD digital printing replicates natural wood grain with authentic warmth and texture.",
      },
      {
        icon: "fa-solid fa-sun",
        title: "UV Stable",
        desc: "Unlike real timber, colour and texture remain stable under intense UV exposure.",
      },
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "Porcelain body is impervious to swelling, rotting, or warping in outdoor conditions.",
      },
      {
        icon: "fa-solid fa-broom",
        title: "Easy Clean",
        desc: "Smooth-sealed surface resists dirt and biological growth for hassle-free upkeep.",
      },
      {
        icon: "fa-solid fa-leaf",
        title: "Eco-Friendly",
        desc: "No timber harvested — preserves forests while delivering natural wood aesthetics.",
      },
      {
        icon: "fa-solid fa-house",
        title: "Plank Format",
        desc: "Long plank format suits alfresco feature walls, pergola cladding and garden screens.",
      },
    ],
    tech: {
      Material: "Porcelain",
      "Water Absorption": "< 0.1%",
      "Frost Resistance": "Class F2",
      Finish: "Matt",
      "Breaking Strength": "> 1500 N",
      Thickness: "9 mm",
      "Weight (per m²)": "19 kg",
      "Chemical Resistance": "Class A",
    },
  },
  {
    id: 2,
    badge: "DESIGNER",
    tag: "BRICK EFFECT",
    title: "Manhattan Brick Effect",
    description:
      "Industrial-chic brick-face porcelain with authentic pressed texture and subtle colour variation. Perfect for urban courtyard and alfresco walls.",
    image: "./images/outdoor/Manhattan Brick.jpg",
    gallery: [
      "./images/outdoor/Manhattan Brick 1.png",
      "./images/outdoor/Manhattan Brick 2.png",
      "./images/outdoor/Manhattan Brick 3.png",
    ],
    texture: "Brick",
    colours: 3,
    finishes: 2,
    finish: ["Matt", "Textured"],
    sizes: ["200×400", "300×600"],
    surface: ["Weather Resistant", "Frost Resistant", "UV Stable"],
    colors: ["Charcoal", "Terracotta", "Cream"],
    colorsHex: { Charcoal: "#2e2a26", Terracotta: "#c1604a", Cream: "#f0ebe0" },
    colorImages: {
      Charcoal: "./images/outdoor/Manhattan Brick 2.png",
      Terracotta: "./images/outdoor/Manhattan Brick 1.png",
      Cream: "./images/outdoor/Manhattan Brick 3.png",
    },
    finishImages: {
      Matt: "./images/outdoor/Manhattan Brick 2.png",
      Textured: "./images/outdoor/Manhattan Brick 3.png",
    },
    sizeImages: {
      "200×400": "./images/outdoor/Manhattan Brick 3.png",
      "300×600": "./images/outdoor/Manhattan Brick 2.png",
    },
    features: [
      {
        icon: "fa-solid fa-cubes",
        title: "Pressed Brick Texture",
        desc: "Deep embossed surface replicates authentic brick face with mortar joint detail.",
      },
      {
        icon: "fa-solid fa-snowflake",
        title: "Frost Resistant",
        desc: "Porcelain vitrification ensures zero water absorption in freeze-thaw conditions.",
      },
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "Full-body colour means chips and scratches remain invisible over time.",
      },
      {
        icon: "fa-solid fa-broom",
        title: "Low Maintenance",
        desc: "Non-porous surface resists staining, moss, and biological growth.",
      },
      {
        icon: "fa-solid fa-ruler-combined",
        title: "Consistent Sizing",
        desc: "Machine-made precision allows tight tolerances and clean installation.",
      },
      {
        icon: "fa-solid fa-city",
        title: "Urban Aesthetic",
        desc: "Ideal for loft-style gardens, feature columns and contemporary façades.",
      },
    ],
    tech: {
      Material: "Porcelain",
      "Water Absorption": "< 0.1%",
      "Frost Resistance": "Class F2",
      Surface: "Textured Matt",
      "Breaking Strength": "> 1600 N",
      Thickness: "9 mm",
      "Weight (per m²)": "20 kg",
      "Chemical Resistance": "Class A",
    },
  },
  {
    id: 3,
    badge: "BESTSELLER",
    tag: "STONE CLADDING",
    title: "Himalayan Slate Cladding",
    description:
      "Dramatic split-face slate in deep charcoal with natural silver veining. Ideal for feature walls, garden boundaries and façade cladding.",
    image: "./images/outdoor_wall_img1.jpg",
    gallery: [
      "./images/outdoor/Himalayan1.png",
      "./images/outdoor/Himalayan2.png",
      "./images/outdoor/Himalayan3.png",
      "./images/outdoor/outdoor2.jpg",
    ],
    texture: "Slate",
    colours: 3,
    finishes: 2,
    finish: ["Natural", "Textured"],
    sizes: ["300×300", "300×600", "600×600"],
    surface: ["Weather Resistant", "Frost Resistant"],
    colors: ["Charcoal", "Slate", "Grey"],
    colorsHex: { Charcoal: "#36454F", Slate: "#708090", Grey: "#808080" },
    colorImages: {
      Charcoal: "./images/outdoor/Himalayan1.png",
      Slate: "./images/outdoor/Himalayan2.png",
      Grey: "./images/outdoor/Himalayan3.png",
    },
    finishImages: {
      Natural: "./images/outdoor/Himalayan1.png",
      Textured: "./images/outdoor/Himalayan3.png",
    },
    sizeImages: {
      "300×300": "./images/outdoor/Himalayan1.png",
      "300×600": "./images/outdoor/Himalayan2.png",
      "600×600": "./images/outdoor/outdoor2.jpg",
    },
    features: [
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "Engineered to withstand heavy rainfall, humidity, and outdoor moisture without degrading.",
      },
      {
        icon: "fa-solid fa-snowflake",
        title: "Frost Resistant",
        desc: "Low water absorption prevents cracking in freeze-thaw cycles, suitable for all climates.",
      },
      {
        icon: "fa-solid fa-sun",
        title: "UV Stable",
        desc: "Colour-stable pigments resist fading from prolonged sun exposure.",
      },
      {
        icon: "fa-solid fa-leaf",
        title: "Anti-Algae",
        desc: "Surface treatment inhibits biological growth, keeping walls clean longer.",
      },
      {
        icon: "fa-solid fa-ruler-combined",
        title: "Split-Face Texture",
        desc: "Natural split surface creates depth and shadow play for dramatic wall effect.",
      },
      {
        icon: "fa-solid fa-recycle",
        title: "Eco Sourced",
        desc: "Responsibly quarried natural stone with low environmental footprint.",
      },
    ],
    tech: {
      Material: "Natural Slate",
      "Water Absorption": "< 0.5%",
      "Frost Resistance": "Class F2",
      "Slip Resistance": "R11",
      "Breaking Strength": "> 1300 N",
      Thickness: "10–15 mm",
      "Weight (per m²)": "22 kg",
      "Chemical Resistance": "Class B",
    },
  },
  {
    id: 4,
    badge: "LUXURY",
    tag: "MARBLE EFFECT",
    title: "Calacatta Outdoor Marble",
    description:
      "The grandeur of Calacatta marble in a weather-resistant porcelain format. Brings luxury interior aesthetics to covered outdoor living spaces.",
    image: "./images/outdoor/Calacatta.jpg",
    gallery: [
      "./images/outdoor/Calacatta1.jpg",
      "./images/outdoor/Calacatta2.jpg",
      "./images/outdoor/Calacatta3.jpg",
      "./images/outdoor/Calacatta4.jpg",
    ],
    texture: "Marble",
    colours: 2,
    finishes: 2,
    finish: ["Glazed", "Matt"],
    sizes: ["600×600", "600×1200"],
    surface: ["Weather Resistant", "UV Stable"],
    colors: ["Ivory", "Grey"],
    colorsHex: { Ivory: "#f5f0e8", Grey: "#5b5c5d" },
    colorImages: {
      Ivory: "./images/outdoor/Calacatta1.jpg",
      Grey: "./images/outdoor/Calacatta4.jpg",
    },
    finishImages: {
      Glazed: "./images/outdoor/Calacatta3.jpg",
      Matt: "./images/outdoor/Calacatta4.jpg",
    },
    sizeImages: {
      "600×600": "./images/outdoor/Calacatta3.jpg",
      "600×1200": "./images/outdoor/Calacatta2.jpg",
    },
    features: [
      {
        icon: "fa-solid fa-gem",
        title: "Marble Luxury",
        desc: "Photorealistic Calacatta veining pattern gives premium marble aesthetics at lower cost.",
      },
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "Porcelain body maintains integrity in outdoor covered or sheltered applications.",
      },
      {
        icon: "fa-solid fa-sun",
        title: "UV Stable",
        desc: "White and grey tones resist yellowing and discolouration from sun exposure.",
      },
      {
        icon: "fa-solid fa-shield-halved",
        title: "Scratch Resistant",
        desc: "Hard glaze surface resists scratching from outdoor furniture and garden tools.",
      },
      {
        icon: "fa-solid fa-ruler-combined",
        title: "Large Format",
        desc: "600×1200 mm format creates seamless, expansive wall surfaces with minimal grout lines.",
      },
      {
        icon: "fa-solid fa-spa",
        title: "Premium Finish",
        desc: "Ideal for luxury poolside walls, covered terraces and alfresco entertainment areas.",
      },
    ],
    tech: {
      Material: "Glazed Porcelain",
      "Water Absorption": "< 0.1%",
      "Frost Resistance": "Class F1",
      Finish: "Glazed / Matt",
      "Breaking Strength": "> 1800 N",
      Thickness: "9 mm",
      "Weight (per m²)": "21 kg",
      "Chemical Resistance": "Class A",
    },
  },
  {
    id: 5,
    badge: "NEW",
    tag: "GEOMETRIC",
    title: "Hexa Stone Series",
    description:
      "Bold hexagonal stone-effect porcelain tiles that bring geometric precision and natural texture to outdoor walls and paved surfaces. A striking modern choice for garden features and contemporary facades.",
    image: "./images/outdoor/Hexa.jpg",
    gallery: [
      "./images/outdoor/Hexa1.jpg",
      "./images/outdoor/Hexa2.jpg",
      "./images/outdoor/Hexa3.jpg",
    ],
    texture: "Stone",
    colours: 3,
    finishes: 2,
    finish: ["Matt", "Textured"],
    sizes: ["200×230", "300×345"],
    surface: ["Weather Resistant", "Frost Resistant", "UV Stable"],
    colors: ["Charcoal", "Sandstone", "Ivory"],
    colorsHex: { Charcoal: "#3b3a36", Sandstone: "#c8a97e", Ivory: "#f5f0e8" },
    colorImages: {
      Charcoal: "./images/outdoor/Hexa1.jpg",
      Sandstone: "./images/outdoor/Hexa2.jpg",
      Ivory: "./images/outdoor/Hexa3.jpg",
    },
    finishImages: {
      Matt: "./images/outdoor/Hexa1.jpg",
      Textured: "./images/outdoor/Hexa2.jpg",
    },
    sizeImages: {
      "200×230": "./images/outdoor/Hexa1.jpg",
      "300×345": "./images/outdoor/Hexa3.jpg",
    },
    features: [
      {
        icon: "fa-solid fa-shapes",
        title: "Hexagonal Format",
        desc: "Unique six-sided format creates eye-catching geometric patterns on any outdoor surface.",
      },
      {
        icon: "fa-solid fa-snowflake",
        title: "Frost Resistant",
        desc: "Dense porcelain body withstands freeze-thaw cycles without cracking or spalling.",
      },
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "Sealed surface repels moisture and resists weathering in all outdoor conditions.",
      },
      {
        icon: "fa-solid fa-sun",
        title: "UV Stable",
        desc: "Colour-fast pigments maintain vibrancy even under prolonged direct sunlight.",
      },
      {
        icon: "fa-solid fa-ruler-combined",
        title: "Precision Cut",
        desc: "Machine-cut edges ensure tight, consistent joints for a clean geometric finish.",
      },
      {
        icon: "fa-solid fa-city",
        title: "Design Statement",
        desc: "Perfect for feature walls, courtyard floors and decorative garden panels.",
      },
    ],
    tech: {
      Material: "Porcelain",
      "Water Absorption": "< 0.1%",
      "Frost Resistance": "Class F2",
      Finish: "Matt / Textured",
      "Breaking Strength": "> 1500 N",
      Thickness: "9 mm",
      "Weight (per m²)": "20 kg",
      "Chemical Resistance": "Class A",
    },
  },
  {
    id: 6,
    badge: "PREMIUM",
    tag: "NATURAL STONE",
    title: "Granite Rock Paver",
    description:
      "Hard-wearing natural granite pavers with a robust split-face finish. Built for high-traffic outdoor areas, driveways and garden pathways where durability meets raw natural beauty.",
    image: "./images/outdoor/Granite.jpg",
    gallery: [
      "./images/outdoor/Granite1.jpg",
      "./images/outdoor/Granite2.jpg",
      "./images/outdoor/Granite3.jpg",
      "./images/outdoor/Granite4.jpg",
    ],
    texture: "Stone",
    colours: 3,
    finishes: 2,
    finish: ["Natural", "Flamed"],
    sizes: ["300×300", "400×400", "600×600"],
    surface: ["Weather Resistant", "Frost Resistant", "Slip Resistant"],
    colors: ["Grey", "Charcoal", "Sandstone"],
    colorsHex: { Grey: "#9fa3aa", Charcoal: "#2e2a26", Sandstone: "#c8a97e" },
    colorImages: {
      Grey: "./images/outdoor/Granite1.jpg",
      Charcoal: "./images/outdoor/Granite2.jpg",
      Sandstone: "./images/outdoor/Granite3.jpg",
    },
    finishImages: {
      Natural: "./images/outdoor/Granite1.jpg",
      Flamed: "./images/outdoor/Granite2.jpg",
    },
    sizeImages: {
      "300×300": "./images/outdoor/Granite4.jpg",
      "400×400": "./images/outdoor/Granite2.jpg",
      "600×600": "./images/outdoor/Granite1.jpg",
    },
    features: [
      {
        icon: "fa-solid fa-mountain",
        title: "Natural Granite",
        desc: "100% natural granite with unique grain patterns and superior hardness rating.",
      },
      {
        icon: "fa-solid fa-shoe-prints",
        title: "Slip Resistant",
        desc: "Flamed and split-face finishes provide excellent grip in wet outdoor conditions.",
      },
      {
        icon: "fa-solid fa-snowflake",
        title: "Frost Resistant",
        desc: "Extremely low porosity granite performs flawlessly in harsh cold climates.",
      },
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "Dense igneous stone naturally repels water and resists surface erosion.",
      },
      {
        icon: "fa-solid fa-truck",
        title: "Heavy Duty",
        desc: "Suitable for driveways, patios and commercial outdoor areas with heavy foot traffic.",
      },
      {
        icon: "fa-solid fa-clock",
        title: "Long Lasting",
        desc: "Natural granite outlasts most engineered materials with minimal maintenance required.",
      },
    ],
    tech: {
      Material: "Natural Granite",
      "Water Absorption": "< 0.2%",
      "Frost Resistance": "Class F2",
      "Slip Resistance": "R11",
      "Breaking Strength": "> 2000 N",
      Thickness: "20–30 mm",
      "Weight (per m²)": "50 kg",
      "Chemical Resistance": "Class B",
    },
  },
  {
    id: 7,
    badge: "TRENDING",
    tag: "MOROCCAN STYLE",
    title: "Moroccan Mosaic Tile",
    description:
      "Vibrant hand-painted Moroccan-inspired mosaic tiles with intricate geometric patterns. Adds exotic artisan character to outdoor walls, niches and decorative garden features.",
    image: "./images/outdoor/Moroccan.jpg",
    gallery: [
      "./images/outdoor/Moroccan1.jpg",
      "./images/outdoor/Moroccan2.jpg",
      "./images/outdoor/Moroccan3.jpg",
      "./images/outdoor/Moroccan4.jpg",
    ],
    texture: "Rustic",
    colours: 4,
    finishes: 2,
    finish: ["Glazed", "Matt"],
    sizes: ["100×100", "200×200", "300×300"],
    surface: ["Weather Resistant", "UV Stable"],
    colors: ["Terracotta", "Ivory", "Sandstone", "Charcoal"],
    colorsHex: {
      Terracotta: "#c1604a",
      Ivory: "#f5f0e8",
      Sandstone: "#c8a97e",
      Charcoal: "#2e2a26",
    },
    colorImages: {
      Terracotta: "./images/outdoor/Moroccan1.jpg",
      Ivory: "./images/outdoor/Moroccan2.jpg",
      Sandstone: "./images/outdoor/Moroccan3.jpg",
      Charcoal: "./images/outdoor/Moroccan4.jpg",
    },
    finishImages: {
      Matt: "./images/outdoor/Moroccan3.jpg",
      Glazed: "./images/outdoor/Moroccan4.jpg",
    },
    sizeImages: {
      "100×100": "./images/outdoor/Moroccan3.jpg",
      "200×200": "./images/outdoor/Moroccan4.jpg",
      "300×300": "./images/outdoor/Moroccan2.jpg",
    },
    features: [
      {
        icon: "fa-solid fa-palette",
        title: "Hand Painted",
        desc: "Artisan hand-painted glazes deliver authentic Moroccan colour and pattern depth.",
      },
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "Glazed surface withstands outdoor humidity and rainfall without colour loss.",
      },
      {
        icon: "fa-solid fa-sun",
        title: "UV Stable",
        desc: "Rich tones are kiln-locked for lasting vibrancy in direct sunlight.",
      },
      {
        icon: "fa-solid fa-star",
        title: "Artisan Quality",
        desc: "Each tile carries subtle hand-crafted variation for authentic mosaic character.",
      },
      {
        icon: "fa-solid fa-building",
        title: "Feature Wall Ready",
        desc: "Ideal for garden niches, courtyard accent walls and outdoor kitchen splashbacks.",
      },
      {
        icon: "fa-solid fa-globe",
        title: "Exotic Aesthetic",
        desc: "Brings the rich decorative tradition of Moroccan zellige to any outdoor space.",
      },
    ],
    tech: {
      Material: "Glazed Ceramic",
      "Water Absorption": "1–3%",
      "Frost Resistance": "Class F1",
      Finish: "Glazed / Matt",
      "Breaking Strength": "> 900 N",
      Thickness: "8 mm",
      "Weight (per m²)": "17 kg",
      "Chemical Resistance": "Class A",
    },
  },
  {
    id: 8,
    badge: "CLASSIC",
    tag: "QUARRY TILE",
    title: "Heritage Quarry Tile",
    description:
      "Traditional unglazed quarry tiles with a dense, earthy texture and timeless appeal. A heritage choice for outdoor patios, courtyards and period-style garden walls.",
    image: "./images/outdoor/Heritage.jpg",
    gallery: [
      "./images/outdoor/Heritage1.jpg",
      "./images/outdoor/Heritage2.jpg",
      "./images/outdoor/Heritage3.jpg",
      "./images/outdoor/Heritage4.jpg",
    ],
    texture: "Rustic",
    colours: 3,
    finishes: 1,
    finish: ["Natural"],
    sizes: ["150×150", "200×200", "300×300"],
    surface: ["Weather Resistant", "Slip Resistant", "UV Stable"],
    colors: ["Terracotta", "Sandstone", "Charcoal"],
    colorsHex: {
      Terracotta: "#c1604a",
      Sandstone: "#c8a97e",
      Charcoal: "#3b3a36",
    },
    colorImages: {
      Terracotta: "./images/outdoor/Heritage1.jpg",
      Sandstone: "./images/outdoor/Heritage2.jpg",
      Charcoal: "./images/outdoor/Heritage3.jpg",
    },
    finishImages: { Natural: "./images/outdoor/Heritage4.jpg" },
    sizeImages: {
      "150×150": "./images/outdoor/Heritage2.jpg",
      "200×200": "./images/outdoor/Heritage3.jpg",
      "300×300": "./images/outdoor/Heritage4.jpg",
    },
    features: [
      {
        icon: "fa-solid fa-fire",
        title: "Kiln Fired",
        desc: "High-temperature firing produces a dense, hard-wearing unglazed surface.",
      },
      {
        icon: "fa-solid fa-shoe-prints",
        title: "Slip Resistant",
        desc: "Natural unglazed texture provides reliable grip on wet outdoor surfaces.",
      },
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "Dense clay body naturally resists moisture penetration and outdoor weathering.",
      },
      {
        icon: "fa-solid fa-sun",
        title: "UV Stable",
        desc: "Natural mineral pigments retain warm earthy tones without fading outdoors.",
      },
      {
        icon: "fa-solid fa-clock",
        title: "Timeless Appeal",
        desc: "Classic quarry tile aesthetic suits traditional, rustic and heritage garden styles.",
      },
      {
        icon: "fa-solid fa-leaf",
        title: "Low Maintenance",
        desc: "Naturally robust surface requires only basic cleaning to maintain its character.",
      },
    ],
    tech: {
      Material: "Unglazed Clay",
      "Water Absorption": "2–4%",
      "Frost Resistance": "Class F1",
      "Slip Resistance": "R10",
      "Breaking Strength": "> 1000 N",
      Thickness: "12 mm",
      "Weight (per m²)": "24 kg",
      "Chemical Resistance": "Class B",
    },
  },
  {
    id: 9,
    badge: "BOLD",
    tag: "COBBLESTONE",
    title: "Rustic Cobblestone Paver",
    description:
      "Tumbled cobblestone-effect porcelain pavers with an authentically aged and irregular surface. Ideal for garden pathways, driveways and rustic outdoor entertaining areas.",
    image: "./images/outdoor/Cobblestone.jpg",
    gallery: [
      "./images/outdoor/Cobblestone1.png",
      "./images/outdoor/Cobblestone2.png",
      "./images/outdoor/Cobblestone3.png",
      "./images/outdoor/Cobblestone4.jpg",
    ],
    texture: "Stone",
    colours: 3,
    finishes: 2,
    finish: ["Tumbled", "Natural"],
    sizes: ["100×100", "200×200", "300×300"],
    surface: ["Weather Resistant", "Frost Resistant", "Slip Resistant"],
    colors: ["Sandstone", "Grey", "Charcoal"],
    colorsHex: { Sandstone: "#c8a97e", Grey: "#9fa3aa", Charcoal: "#2e2a26" },
    colorImages: {
      Sandstone: "./images/outdoor/Cobblestone2.png",
      Grey: "./images/outdoor/Cobblestone4.jpg",
      Charcoal: "./images/outdoor/Cobblestone3.png",
    },
    finishImages: {
      Tumbled: "./images/outdoor/Cobblestone1.png",
      Natural: "./images/outdoor/Cobblestone2.png",
    },
    sizeImages: {
      "100×100": "./images/outdoor/Cobblestone2.png",
      "200×200": "./images/outdoor/Cobblestone3.png",
      "300×300": "./images/outdoor/Cobblestone4.jpg",
    },
    features: [
      {
        icon: "fa-solid fa-road",
        title: "Cobblestone Effect",
        desc: "Tumbled edges replicate centuries-old cobblestone character and aged surface texture.",
      },
      {
        icon: "fa-solid fa-snowflake",
        title: "Frost Resistant",
        desc: "Porcelain core with negligible water absorption ensures year-round outdoor performance.",
      },
      {
        icon: "fa-solid fa-shoe-prints",
        title: "Slip Resistant",
        desc: "Textured tumbled surface provides safe underfoot grip in wet and damp conditions.",
      },
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "Sealed porcelain body resists staining, erosion and outdoor moisture damage.",
      },
      {
        icon: "fa-solid fa-house",
        title: "Driveway Ready",
        desc: "Heavy-duty format suitable for pedestrian paths, driveways and garden courtyards.",
      },
      {
        icon: "fa-solid fa-clock",
        title: "Aged Character",
        desc: "Tumbled finish lends an authentic heritage feel to any outdoor landscape design.",
      },
    ],
    tech: {
      Material: "Porcelain",
      "Water Absorption": "< 0.1%",
      "Frost Resistance": "Class F2",
      "Slip Resistance": "R11",
      "Breaking Strength": "> 1700 N",
      Thickness: "20 mm",
      "Weight (per m²)": "46 kg",
      "Chemical Resistance": "Class A",
    },
  },
  {
    id: 10,
    badge: "TRENDING",
    tag: "CONCRETE EFFECT",
    title: "Nordic Concrete Tile",
    description:
      "Minimalist Scandinavian-inspired concrete-effect porcelain in cool, muted tones. Delivers a refined industrial aesthetic for contemporary outdoor terraces and feature walls.",
    image: "./images/outdoor/NordicConcrete.jpg",
    gallery: [
      "./images/outdoor/NordicConcrete1.png",
      "./images/outdoor/NordicConcrete2.png",
      "./images/outdoor/NordicConcrete3.png",
      "./images/outdoor/NordicConcrete4.jpg",
    ],
    texture: "Stone",
    colours: 3,
    finishes: 2,
    finish: ["Matt", "Textured"],
    sizes: ["300×600", "600×600", "600×1200"],
    surface: ["Weather Resistant", "Frost Resistant", "Anti-Algae"],
    colors: ["Grey", "Ivory", "Charcoal"],
    colorsHex: { Grey: "#9fa3aa", Ivory: "#f5f0e8", Charcoal: "#2e2a26" },
    colorImages: {
      Grey: "./images/outdoor/NordicConcrete1.png",
      Ivory: "./images/outdoor/NordicConcrete2.png",
      Charcoal: "./images/outdoor/NordicConcrete4.jpg",
    },
    finishImages: {
      Matt: "./images/outdoor/NordicConcrete1.png",
      Textured: "./images/outdoor/NordicConcrete2.png",
    },
    sizeImages: {
      "300×600": "./images/outdoor/NordicConcrete2.png",
      "600×600": "./images/outdoor/NordicConcrete4.jpg",
      "600×1200": "./images/outdoor/NordicConcrete1.png",
    },
    features: [
      {
        icon: "fa-solid fa-industry",
        title: "Concrete Aesthetic",
        desc: "Fine micro-concrete texture delivers authentic Scandinavian raw industrial character.",
      },
      {
        icon: "fa-solid fa-snowflake",
        title: "Frost Resistant",
        desc: "Full-body porcelain with minimal water absorption for reliable cold climate performance.",
      },
      {
        icon: "fa-solid fa-leaf",
        title: "Anti-Algae",
        desc: "Surface treatment prevents biological growth on outdoor terraces and feature walls.",
      },
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "Non-porous surface withstands heavy rain and humidity without staining or damage.",
      },
      {
        icon: "fa-solid fa-ruler",
        title: "Large Format",
        desc: "600×1200 format creates seamless, expansive outdoor surfaces with minimal grout lines.",
      },
      {
        icon: "fa-solid fa-spa",
        title: "Minimalist Design",
        desc: "Cool muted tones suit contemporary Scandinavian garden and terrace design schemes.",
      },
    ],
    tech: {
      Material: "Full-Body Porcelain",
      "Water Absorption": "< 0.1%",
      "Frost Resistance": "Class F2",
      Finish: "Matt / Textured",
      "Breaking Strength": "> 1700 N",
      Thickness: "9 mm",
      "Weight (per m²)": "21 kg",
      "Chemical Resistance": "Class A",
    },
  },
  {
    id: 11,
    badge: "PREMIUM",
    tag: "NATURAL STONE",
    title: "Travertine Classic",
    description:
      "Timeless natural travertine with its signature pitted surface and warm ivory tones. A refined choice for outdoor terraces, pool surrounds and classic Mediterranean garden settings.",
    image: "./images/outdoor/Travertine.jpg",
    gallery: [
      "./images/outdoor/Travertine1.jpg",
      "./images/outdoor/Travertine2.jpg",
      "./images/outdoor/Travertine3.jpg",
    ],
    texture: "Stone",
    colours: 3,
    finishes: 3,
    finish: ["Natural", "Honed", "Tumbled"],
    sizes: ["300×300", "300×600", "600×600"],
    surface: ["Weather Resistant", "UV Stable", "Slip Resistant"],
    colors: ["Ivory", "Beige", "Sandstone"],
    colorsHex: { Ivory: "#f5f0e8", Beige: "#d8c9a3", Sandstone: "#c8a97e" },
    colorImages: {
      Ivory: "./images/outdoor/Travertine2.jpg",
      Beige: "./images/outdoor/Travertine1.jpg",
      Sandstone: "./images/outdoor/Travertine3.jpg",
    },
    finishImages: {
      Natural: "./images/outdoor/Travertine1.jpg",
      Honed: "./images/outdoor/Travertine2.jpg",
      Tumbled: "./images/outdoor/Travertine3.jpg",
    },
    sizeImages: {
      "300×300": "./images/outdoor/Travertine1.jpg",
      "300×600": "./images/outdoor/Travertine2.jpg",
      "600×600": "./images/outdoor/Travertine3.jpg",
    },
    features: [
      {
        icon: "fa-solid fa-mountain",
        title: "Natural Travertine",
        desc: "Authentic natural travertine with characteristic pitting and linear vein patterns.",
      },
      {
        icon: "fa-solid fa-water",
        title: "Pool Surround Ready",
        desc: "Honed and tumbled finishes provide safe, non-slip surfaces around pool areas.",
      },
      {
        icon: "fa-solid fa-sun",
        title: "UV Stable",
        desc: "Warm ivory and beige tones remain consistent without bleaching under outdoor sun.",
      },
      {
        icon: "fa-solid fa-cloud-rain",
        title: "Weather Resistant",
        desc: "Sealed natural stone resists moisture penetration and outdoor surface erosion.",
      },
      {
        icon: "fa-solid fa-shoe-prints",
        title: "Slip Resistant",
        desc: "Tumbled and honed finishes meet outdoor slip resistance standards for safe use.",
      },
      {
        icon: "fa-solid fa-spa",
        title: "Mediterranean Style",
        desc: "Classic travertine aesthetic complements both traditional and resort-style outdoor spaces.",
      },
    ],
    tech: {
      Material: "Natural Travertine",
      "Water Absorption": "1–3%",
      "Frost Resistance": "Class F1",
      "Slip Resistance": "R10",
      "Breaking Strength": "> 1100 N",
      Thickness: "12–20 mm",
      "Weight (per m²)": "28 kg",
      "Chemical Resistance": "Class B",
    },
  },
];

const FEATURED_IDS = [0, 2, 4, 6];
